Repository Arquisoft/wichat_en1a, pull requests merged in 2025-04, with the labels that each got.

#116 Modification of the placeholder readme with information fit with our project
  README.md
  webapp/public/GameDescriptionImage.png
  webapp/public/android-chrome-192x192.png
  webapp/public/android-chrome-512x512.png
  webapp/public/apple-touch-icon.png
  webapp/public/favicon-16x16.png
  webapp/public/favicon-32x32.png
  webapp/public/favicon.ico
  webapp/public/logo192.png
  webapp/public/logo512.png
  webapp/public/manifest.json
  webapp/public/wichat logo.png
  webapp/src/components/AboutUsFooter.js
  webapp/src/locales/EN.json
  webapp/src/locales/ES.json
  webapp/src/windows/IndexPage.js
Labels: documentation 📝

#112 feature/gateway-service-gameservice
  gameservice/src/routes/game-routes.js
  gameservice/src/services/game-service.js
  gameservice/test/game-service.test.js
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/package-lock.json
  gatewayservice/package.json
Labels: backend ⚙️

#118 fix: Change the get questions call to get them from the db
  webapp/package-lock.json
  webapp/package.json
  webapp/src/tests/GamePage.test.js
  webapp/src/windows/GamePage.js
Labels: bug 🪲

#127 Feature/gateway service gameservice add more fields
  gameservice/src/models/score-model.js
  gameservice/src/routes/game-routes.js
  gameservice/src/services/game-service.js
  gameservice/test/game-service.test.js
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
Labels: backend ⚙️

#130 fix security problems
  gameservice/src/routes/game-routes.js
  gameservice/src/services/game-service.js
  gameservice/test/game-service.test.js
Labels: backend ⚙️

#133 fix security problems and coverage of game service
  gameservice/src/services/game-service.js
  gameservice/test/game-service.test.js
Labels: backend ⚙️

#210 fix: Add grafana and prometheus to production
  docker-compose.yml
Labels: deployment
