Repository Arquisoft/wichat_en1a, pull requests merged in 2025-03, with the labels that each got.

#63 Feature/login&signup, fix of tests, and implementation of color pallete
  docker-compose.yml
  questionservice/Dockerfile
  webapp/package-lock.json
  webapp/package.json
  webapp/public/colorPalleteProposed.png
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AboutUsFooter.js
  webapp/src/components/AddUser.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
  webapp/src/components/NavBar.js
  webapp/src/locales/EN.json
  webapp/src/locales/ES.json
  webapp/src/windows/HomePage.js
  webapp/src/windows/IndexPage.js
  webapp/src/windows/LogInOrUpPage.js
Labels: frontend 🪄

#64 Feature/signup
  webapp/package-lock.json
  webapp/package.json
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
  webapp/src/components/NavBar.js
  webapp/src/locales/EN.json
  webapp/src/locales/ES.json
  webapp/src/windows/LogInOrUpPage.js
Labels: frontend 🪄

#72 Change the generate questions
  questionservice/src/services/question-generator.js
Labels: backend ⚙️

#82 Fixed the images issue in the home page
  webapp/src/windows/HomePage.js
Labels: frontend 🪄

#97 Fix/cuality gate
  .gitignore
  users/userservice/user-service.js
  webapp/e2e/features/register-form.feature
  webapp/e2e/steps/register-form.steps.js
  webapp/src/App.js
  webapp/src/LoggedInRoutes.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/AiChat.js
  webapp/src/components/GameComponent.js
  webapp/src/components/Login.js
  webapp/src/tests/GameComponent.test.js
  webapp/src/windows/GamePage.js
  webapp/src/windows/IndexPage.js
  webapp/src/windows/LogInOrUpPage.js
Labels: bug 🪲, frontend 🪄

#98 feature: Generating questions periodically
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/src/index.js
  questionservice/src/models/question-model.js
  questionservice/src/services/question-worker.js
Labels: backend ⚙️
